name: krew

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  krew:
    runs-on: ubuntu-latest
    steps:
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.32
        with:
          plugin-name: kubectl-popeye
